### PR TITLE
Develop a tool for generating SLIM surface datasets (surdat files)

### LINKED ISSUE #36: Add metadata to mml_surdat files, ideally using a mksurdat tool than can also generate such files
We need to add metadata to the mml_surdat files so that the quantities and units for each variable is more clearly defined. We should use the CF standards for defining the files. Right now the files just have the variable names as follows:

dimensions:
	time = 12 ;
	lsmlat = 96 ;
	lsmlon = 144 ;
variables:
	double alb_snf(time, lsmlat, lsmlon) ;
	double bucketdepth(time, lsmlat, lsmlon) ;
	double alb_svd(time, lsmlat, lsmlon) ;
	double soil_type(time, lsmlat, lsmlon) ;
	double alb_svf(time, lsmlat, lsmlon) ;
	double alb_gvd(time, lsmlat, lsmlon) ;
	double snowmask(time, lsmlat, lsmlon) ;
	double alb_gvf(time, lsmlat, lsmlon) ;
	double roughness(time, lsmlat, lsmlon) ;
	double soil_tk_2d(time, lsmlat, lsmlon) ;
	double alb_gnd(time, lsmlat, lsmlon) ;
	double alb_gnf(time, lsmlat, lsmlon) ;
	double glc_tk_2d(time, lsmlat, lsmlon) ;
	double soil_cv_2d(time, lsmlat, lsmlon) ;
	double glc_mask(time, lsmlat, lsmlon) ;
	double glc_cv_2d(time, lsmlat, lsmlon) ;
	double evap_res(time, lsmlat, lsmlon) ;
	double emissivity(time, lsmlat, lsmlon) ;
	double lsmlon(lsmlon) ;
	double lsmlat(lsmlat) ;
	int64 time(time) ;
	double alb_snd(time, lsmlat, lsmlon) ;

longnames, and units and other standard attributes: mode, bounds, calendar, axis, and coordinates. And global attributes: references, title, institution, Conventions, comment, history, and things like the user who created and how.

CF conventions are here:

https://cfconventions.org/

### PR DESCRIPTION
**Pull request by slevis-lmwg**
Fixes #36 

As of opening this PR, my code reads a ctsm history file and outputs a file that contains:
glc_mask
lsmlon
lsmlat

Note that I started this branch from my surdat_modifier branch to avoid repeating a bunch of shared python work between that branch and this one.

I need to check with @marysa what calculations I need to include to generate a surdat file.

### CODE REVIEW

**Comment by slevisconsulting** [comment]
Notes from today's meeting with @marysa (@ekluzek present for first half).

First of all, thank you @marysa for taking the time to meet. Feel free to post comments/corrections to this post.

I have copied three relevant files from Marysa to this directory:
`/glade/work/slevis/git_slim/mksurdat_prep`
```
pres_vs_hist_alb_LN_postAGU20190621_corrected_rs.ipynb  
SimpleForcingsWG2017.py
realistic_slim_forcing.py
```
The notebook generates a SLIM surdat file. Marysa helped me become familiar with the contents of the notebook. I have deleted unnecessary code (probably not all) and added clarification comments. It seems reasonable to use the notebook or code from the notebook to build the tool in this PR. It makes sense to me to rename the notebook to mksurdat.ipynb for now. We may rename again according to this [post.](https://github.com/ESCOMP/SimpleLand/pull/69#discussion_r1131724798)

The other two files listed here, one generates a "simple" surdat (no spatial variation) and the other a "realistic" surdat. We didn't discuss them further, so they may or may not come in handy.

**Comment by slevisconsulting** [comment]
I need to update the README in the /tools directory and add a README for this tool.

**Comment by slevisconsulting** [comment]
I generated this file with the jupyter notebook:
`/glade/work/slevis/git_slim/surdat_modifier/python/slim/mksurdat/surdat_20230323.nc`
...and ran this case successfully:
`/glade/u/home/slevis/cases_slim/slim_cam5_som_f09_g16_example`

To review this work, others (@ekluzek, @marysa?, @islasimpson?) could look at and/or run this jupyter notebook draft by checking out my branch and following the instructions in `/glade/work/slevis/git_slim/surdat_modifier/tools/mksurdat/README.mksurdat`

@ekluzek we can discuss in more detail at Stand-up tomorrow.

**Comment by marysa** [comment]
Taking a look at these notebooks now!

**Comment by slevisconsulting** [comment]
Thank you @marysa!
In the last couple of days I have had trouble starting up a jupyter notebook on a casper login, but no trouble on a cheyenne login node. Mentioning in case you encounter the same.

**Comment by marysa** [comment]
oooooh possibly scratch that, I see the .ipynb in your folder, just didn't have them in the copy I pulled from github. I'll copy yours and give it a go!

**Comment by ekluzek** [comment]
@slevisconsulting and I talked about this. This can come in when it's ready. It's completion updates the minor version number of SLIM as it makes SLIM into a complete package. The PR I'm working on is on a different branch, and orthogonal to this, so the order doesn't matter.

This will need to be updated and conflicts resolved to make it compatible with the latest cesm2_1_slim branch. That update will make it easier to see what this actually brings in.

**Review by ekluzek — APPROVED** [review]
I did a rough review. And we went over it together.

We should probably update that review when this is updated to the latest cesm2_1_slim branch, as that will affect what's actually here on the branch.

**Comment by slevis-lmwg** [comment]
In addition to the performed tests that I listed in the [last commit notes](https://github.com/ESCOMP/SimpleLand/pull/71/commits/acbbeb41a461c5a40a7f585b8779a8623df4af31), I also reran the python notebook from this PR and got bit-for-bit the same surdat file from it as before (last file I had generated in March).

**Comment by slevis-lmwg** [comment]
Running the test-suites.

Cheyenne gnu ok, except in some tests I get this NLCOMP difference. @ekluzek is it a problem?
```
Comparison failed between '/glade/work/slevis/git_slim/surdat_modifier/cime/scripts/cases/SMS_D_Lm1_PS.f19_f19_mg17.I2000SlimRsGs.cheyenne_gnu.slim-Monthly.GC.20230512_122012_eb062g/CaseDocs/atm_modelio.nml' with '/glade/p/cgd/tss/ctsm_baselines/slim0.2.002_release-cesm2.1.4/SMS_D_Lm1_PS.f19_f19_mg17.I2000SlimRsGs.cheyenne_gnu.slim-Monthly/CaseDocs/atm_modelio.nml'
  BASE: pio_typename = 'netcdf'
  COMP: pio_typename = 'pnetcdf'
```

Cheyenne intel IN PROGRESS
Izumi NOT STARTED

**Comment by ekluzek** [comment]
@slevis-lmwg I see those differences on occasion as well. I'm not sure why they happen. It's just changing the PIO type so should be identical. We do want to be using pnetcdf, and my baseline is the one without pnetcdf, so yours is correct anyway. Maybe there is a hidden environment variable that is different between the two of us?

**Pull request merged**
